### ISSUE TITLE
함수 조사

### ISSUE THREAD

**Issue by Bymin1018** [EonseokYim/Software_Engineering_Project02#1]
스탯 함수의 인자

struct stat {
dev_t st_dev; /* ID of device containing file */
ino_t st_ino; /* inode number */
mode_t st_mode; /* protection */
nlink_t st_nlink; /* number of hard links */
uid_t st_uid; /* user ID of owner */
gid_t st_gid; /* group ID of owner */
dev_t st_rdev; /* device ID (if special file)
off_t st_size; /* total size, in bytes */
blksize_t st_blksize; /* blocksize for file system I/O */
blkcnt_t st_blocks; /* number of 512B blocks
allocated */
time_t st_atime; /* time of last access */
time_t st_mtime; /* time of last modification */
time_t st_ctime; /* time of last status change */
};

중에
off_t st_size
blkcnt_t st_blocks; 를 사용한다.

**Comment by kanghs9755** [comment]
이렇게 하면 되겠습니다.
