### ISSUE TITLE
stat 구조체 내부 데이터 구조

### ISSUE THREAD

**Issue by EonseokYim** [EonseokYim/Software_Engineering_Project02#31]
struct stat{
    mode_t st_mode; //파일 타입과 퍼미션
    ino_t st_ino;//i-node 번호
    dev_t st_dev; //장치 번호
    dev_t st_rdev; //특수 파일의 장치 번호
    nlink_t st_nlink; //링크 수
    uid_t st_uid;//소유자의 USER ID
    gid_t st_gid; //소유자의 GROUP ID
    off_t st_size; //정규파일의 바이트 수
    time_t st_atime; //마지막 접근 시각
    time_t st_mtime: //마지막 수정 시각
    time_t st_ctime; //마지막 상태 변경 시각
    long st_blksize; // I/O 블록 크기
    long st_blocks;//할항한 블록의 개수
};

**Comment by kml0806** [comment]
잘 보고가요~~

**Comment by kanghs9755** [comment]
좋아요~
