### ISSUE TITLE
날짜비교함수

### ISSUE THREAD

**Issue by kanghs9755** [EonseokYim/Software_Engineering_Project02#4]
void datecmp(void) {
    filetime1();
    int mon1 = time1 -> tm_mon+1;
    int day1 = time1 -> tm_mday;
    filetime2();
    int mon2 = time2 -> tm_mon+1;
    int day2 = time2 -> tm_mday;
    printf("date compare\n");
    if(mon1>mon2)
    {
        printf("text2 is early\n");
    }
    else if (mon1<mon2)
    {
        printf("text1 is early\n");
    }
    else
    {
        if(day1>day2)
        {
            printf("text2 is early\n");
        }
        else if(day1<day2)
        {
            printf("text1 is early\n");
        }
        else
        {
            printf("same time\n");
        }
    }
    return;
}

**Comment by kml0806** [comment]
pull request 넣어주세여
