### ISSUE TITLE
시간비교함수

### ISSUE THREAD

**Issue by kanghs9755** [EonseokYim/Software_Engineering_Project02#5]
void timecmp(void) {
    filetime1();
    int hour1 = time1->tm_hour;
    int min1 = time1->tm_min;
    filetime2();
    int hour2 = time2->tm_hour;
    int min2 = time2->tm_min;
    printf("time compare\n");
    if(hour1>hour2)
    {
        printf("text2 is early\n");
    }
    else if (hour1<hour2)
    {
        printf("text1 is early\n");
    }
    else
    {
        if(min1>min2)
        {
            printf("text2 is early\n");
        }
        else if(min1<min2)
        {
            printf("text1 is early\n");
        }
        else
        {
            printf("same time\n");
        }
    }
    return;
}

**Comment by kml0806** [comment]
잘하셨습니다!!

**Comment by Bymin1018** [comment]
1을 받고 2를 받으면 되는군요!!
